### ISSUE TITLE
Vector memory exhausted on plain text processing

### ISSUE THREAD

**Issue by cspenn** [AdamSpannbauer/lexRankr#16]
When attempting to digest plain text, I hit:

```
Parsing text into sentences and tokens...DONE
Calculating pairwise sentence similarities...
Error: vector memory exhausted (limit reached?)
```

Example is a dataframe with a URL as the first column and the page's text (HTML stripped) as the second column. 

I am attempting to return only the highest LexRanked sentence from the block of text, one per article.

Code:
```
df$summary = lexRankr::lexRank(df$contentraw,
                          docId = df$url,
                          n = 1,
                          continuous = FALSE)
```

Am I doing this wrong?

**Comment by AdamSpannbauer** [comment]
The call you show above is attempting to use the entire contents of `df$contentraw` and produce a single summary sentence from all the text in the column.  As shown in the error, working with a large corpus is very memory intensive and depending on the input size, your system may not be able to handle it.

If you are trying to run the `lexRank` process on one `url` at a time you will need to iterate over the urls yourself or use something such as `data.table`'s `by` operator (example below).  This is less likely to run into the memory issues you experienced.

```r
library(data.table)

dt = data.table(contentraw = c('This is a test sentence.  Second sentence.  Test sentence again.',
                               'This is another document.  More words.  More document words.',
                               'Last doc.  More text doc.  Third sentence.'),
                url = 1:3)

dt[, lexRankr::lexRank(contentraw, 
                       docId = url,
                       n = 1,
                       continuous = FALSE,
                       returnTies = FALSE),
   by = url]

#    url docId sentenceId                 sentence     value
# 1:   1     1        1_1 This is a test sentence. 0.3333333
# 2:   2     2        2_3     More document words. 0.4864865
# 3:   3     3        3_1                Last doc. 0.5000000
```

**Comment by cspenn** [comment]
Many thanks - was trying lapply and ran into similar. Appreciate it!
