### ISSUE TITLE
no sentences above threshold needs verbose error

### ISSUE THREAD

**Issue by AdamSpannbauer** [AdamSpannbauer/lexRankr#2]
`lexRankFromSimil` has threshold option which sets minimal simil scores for edges that are built into graph where pageRank is performed.  Currently no message to user if no edges are above threshold, and code does not produce error in `lexRankFromSimil`.    Error will be produced in `lexRank` due to this issue in the final output step.

Need to include verbose error describing issue and suggesting explanation/workarounds.

**Comment by AdamSpannbauer** [comment]
included check in `lexRankFromSimil` to throw error if all simil values are below threshold

**Comment by Monduiz** [comment]
Is this what the error "
Error: All values in sentence term tfidf matrix are 0.  Similarities would return as NaN" refers to ?

**Comment by AdamSpannbauer** [comment]
that is unrelated to this.  i'll address your question in #11
